[#ftl auto_esc=false]

[#function makeId value]
    [#return value?replace(" ", "_")?replace("/", "-")?replace("{", "_")?replace("}", "_")/]
[/#function]

[#function getMethodColour value]
    [#switch value?upper_case]
        [#case "GET"]
            [#return "success"/]
        [#case "POST"]
            [#return "warning"/]
        [#case "PUT"]
            [#return "info"/]
        [#case "DELETE"]
            [#return "danger"/]
        [#default]
            [#return "light"/]
    [/#switch]
[/#function]